version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn test -f my-app/
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package -f my-app/

artifacts:
  files:
    - target/*
  discard-paths: yes
